Resources:
  createProductTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: notify-about-products

  createProductTopicSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: Artsiom_Rymarchuk@epam.com
      Protocol: email
      FilterPolicy:
        title:
          - "BMW 4-series"
      TopicArn:
        Ref: createProductTopic

  createProductTopicSubscriptionForAnotherTitle:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: kejnovalitnejno@gmail.com
      Protocol: email
      FilterPolicy:
        title:
          - "BMW 2-series"
      TopicArn:
        Ref: createProductTopic
